### PR TITLE
Insert rough working Unpacker

### LINKED ISSUE #65: Add JNI unpacking to IO
As said by @ArcticLight on chat: 

> Pathway's IO module is now going to inherit some packing functionality to make this actually Happen. Hence, merging in the Tempo repo. This is because, re: our previous discussion about how to do JNI graphics within Java, we have taken the opinion that we will be Sad Minecraft, and that Pathway will unpack its natives and fork itself much like Other Launchers do.

I believe we should be able to incorporate the unpacking code from ArcticLight/Tempo, with some minimal clean-up and improvement.

### PR DESCRIPTION
**Pull request by ArcticLight**
This PR adds JNI natives unpacking code (closes #65).

This adds the `Unpacker` class in `com.meteorcode.pathway.io`, based on code written by @ArcticLight for Tempo. 

While there are no unit tests for `Unpacker` due to the nature of its functionality, there is an sbt task (`sbt unpacker-test:assembly`) for building a version of the jar for manually testing it. That should be sufficient, given how challenging it would be to test this code.

Previously, Max said:

# ~~This Merge Request is for testing/review ONLY! Please don't merge it yet!~~

~~This is a rough copy of Tempo's Unpacker utility, spruced up a little with support for custom directory names. I can't build it at the moment, but here's the current state of Pathway Unpacker. We should decide a number of things about this merge before we go ahead and do it, as well as thoroughly testing the code.~~

~~The main outstanding question is this: Do we want to leave it as me/arcticlight/tempo, or rebrand it into a Pathway component?~~

~~Some necessary warnings:~~

#### ~~THIS UTILITY HAS NOT BEEN TESTED YET.~~
~~It was tested (vaguely) when it was in Tempo, but the code has been mangled/changed since then!~~

#### ~~THIS UTILITY READS FROM A `/buildres/` FOLDER!~~
~~We don't currently make this folder during builds!~~

### CODE REVIEW

**Comment by ArcticLight** [comment]
I sincerely apologize for the state of this commit history, I am currently attempting to code outside of an IDE :stuck_out_tongue:

**Comment by hawkw** [comment]
This looks good so far, I'm taking a closer look at your code to make sure. 

With regards to package naming, I think we should either put it directly into the `com.meteorcode.pathway` namespace, or, if you'd like, the `com.meteorcode.common` namespace (if you're planning on re-using this in other projects; `common` could eventually be spun off into a library). Since `Unpacker` isn't serving a purpose directly related to Tempo's core functionality of being a presentation system, it seems weird to namespace this as `tempo`.

As far as patch coverage goes, I imagine this will be a huge pain to write unit tests for, so I suppose I'd accept manual testing as long as we feel like we can reasonably prove that it works.

**Comment by hawkw** [comment]
Since you refer directly to a `.pathway` directory in the default location for `Unpacker`, I think we ought to call this part of Pathway.

**Comment by hawkw** [comment]
As of commit 0fe15da5a426233540b1e1ee862b59ec65ef76d3, natives go to their own directory within the assembled jarfile. Currently, that directory is called `lwjgl-natives/`, but the name can be changed quite easily. 

Now that that's the case, we should finalise this and get it ready to merge in.

**Comment by hawkw** [comment]
Did we ever decide what package `Unpacker` was going to live in?

**Comment by ArcticLight** [comment]
We do not appear to have decided that. Does it live in the arcticlight namespace or is it an official Pathway thingy?

**Comment by hawkw** [comment]
I think it ought to go in the Pathway namespace, if you're okay with that.

**Comment by hawkw** [comment]
Moved to `pathway.io` namespace in adc075fd2f4d32c6a75c2114eae1684b71d6ba2f

**Comment by hawkw** [comment]
ec36d1135531dfd0fec77f47f6c3aa02854d1bf7 fixes an issue where `Unpacker` never creates the natives target directory if it doesn't exist.

I'd like it if `Unpacker` would filter the type of unpacked natives based on the host OS, but that would require additional work. For now, the version in the `cleanup-unpacker` branch _works_.

**Comment by hawkw** [comment]
(also 0f54efb325a2f1ca7607ef2dd2ed206fa16fa84 on `cleanup-unpacker` adds some quick code for manually testing the unpacker. it _could_ eventually be made into a unit test, but we'd need to find some way to specify that that unit test only gets run from a jar build of Pathway, which might be tricky)

**Comment by hawkw** [comment]
This should be ready to merge now. I'd still like to see it only unpack the natives for the current host OS, but I think for now, we'd just like to see this in master so @ArcticLight can start on graphics. I might go back and add OS-checking functionality later.

**Comment by hawkw** [comment]
As of 9585b6feb2440f9a8185135058b37cebd80c4622, you can use `sbt test:assemble` to build a jar file that runs the "red screen test" from Tempo, proving that LWJGL has been unpacked and the classpath has been patched correctly.

**Pull request merged**
